---
- hosts: all
  become: yes

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.git
    - nebula
    - geerlingguy.postfix
    - geerlingguy.apache
    - geerlingguy.mysql
    - geerlingguy.php
    - geerlingguy.php-pecl
    - geerlingguy.php-mysql
    - geerlingguy.composer
    - geerlingguy.drush
    - geerlingguy.drupal-console
